simulation:
  duration_seconds: 3600
  output_report: "network_report.txt"
  log_file: "simulation.log"
# Глобальные константы технологии (чтобы не дублировать в каждой БС)
network_defaults:
  gsm:
    trx_bandwidth_mhz: 0.2  # Физика: 200 кГц на один TRX
    slots_per_trx: 8        # Стандарт TDMA
    sig_slots_per_cell: 2   # Резерв под BCCH/SDCCH

tariffs:
  - id: "basic_01"
    name: "Basic"
    price_per_minute: 1



base_stations:
# Пример 2G станции
# ------------------------------------------------------------------
  # ГИБРИДНЫЙ САЙТ (Multi-RAT): 2G + 5G в центре
  # ------------------------------------------------------------------
  - id: "SITE-CENTRAL-01"
    site:
      x: 500
      y: 500
      height_m: 35
    
    technologies:
      - type: "gsm"
        # Классическая 3-секторная конфигурация 2G
        sectors:
          - cell_id: "SITE-01-G1"
            azimuth: 0
            frequency_mhz: 900
            num_trx: 3
            antenna_type: "directional"        # Емкость: (3*8)-2 = 22 слота
          - cell_id: "SITE-01-G2"
            azimuth: 120
            frequency_mhz: 900
            antenna_type: "directional"  
            num_trx: 2
          - cell_id: "SITE-01-G3"
            azimuth: 240
            frequency_mhz: 900
            num_trx: 2
            antenna_type: "directional"
      - type: "5g_nr"
        # 5G с независимыми азимутами и другой нарезкой секторов
        sectors:
          - cell_id: "SITE-01-N1"
            azimuth: 15       # Смещение относительно GSM для точного покрытия
            frequency_mhz: 3500
            bandwidth_mhz: 100
            mimo_layers: 4
            antenna_type: "directional"
          - cell_id: "SITE-01-N2"
            azimuth: 135
            frequency_mhz: 3500
            bandwidth_mhz: 80
            antenna_type: "directional"
          - cell_id: "SITE-01-N3"
            azimuth: 255
            frequency_mhz: 3500
            bandwidth_mhz: 100
            antenna_type: "directional"
  # ------------------------------------------------------------------
  # СТАНДАРТНЫЙ 2G САЙТ: Окраина города
  # ------------------------------------------------------------------
  - id: "SITE-SUBURB-02"
    site:
      x: 150
      y: 850
      height_m: 25
    
    technologies:
      - type: "gsm"
        sectors:
          - cell_id: "SITE-02-G1"
            azimuth: 45
            frequency_mhz: 1800
            num_trx: 1        # Малая емкость: (1*8)-2 = 6 слотов
          - cell_id: "SITE-02-G2"
            azimuth: 225
            frequency_mhz: 1800
            num_trx: 1



subscribers:
  - name: "Иван"
    surname: "Иванов"
    phone: "1234567890"
    email: "ivan@example.com"
    initial_balance: 100000
    id: "UE-01"
  - name: "Мария"
    surname: "Петрова"
    phone: "1234567891"
    email: "maria@example.com"
    initial_balance: 100000
    id: "UE-02"


user_equipments:
  - id: "UE-01"
  - id: "UE-02"
